class AppText {

  static String selectedLanguage = "ENGLISH";

  static Map<String, Map<String, String>> text = {

    'ENGLISH': {
      'Continue':'Continue',
      'Transparent Pricing, No Hidden fees or Commission':'Transparent Pricing, No Hidden fees or Commission',
      'SUBSCRIPTION':'SUBSCRIPTION',
      'Vehicle RC':'Vehicle RC',
      'Driver Login': 'Driver Login',
      'Payments': 'Payments',
      'Manage Your Payments': 'Manage Your Payments',
      'View payment methods and transaction history.': 'View payment methods and transaction history.',
      'Payment Methods': 'Payment Methods',
      'Google Pay': 'Google Pay',
      'PhonePe': 'PhonePe',
      'Bank Transfer': 'Bank Transfer',
      'Wallet': 'Wallet',
      'Recent Transactions': 'Recent Transactions',
      'Wallet Balance Added': 'Wallet Balance Added',
      'Payout to Metersay': 'Payout to Metersay',
      'Secure Payments': 'Secure Payments',
      'Your payments are encrypted and secured with top-level security.': 'Your payments are encrypted and secured with top-level security.',
      'Learn More': 'Learn More',
      'Registration': 'Registration',
      'Welcome Back!!': 'Welcome Back!!',
      'Upload Documents': 'Upload Documents',
      'Details': 'Details',
      'Settings': 'Settings',
      'Terms and Conditions': 'Terms and Conditions',
      'Account': 'Account',
      'Last Updated: 27 April 2026': 'Last Updated: 27 April 2026',
      'Personal Details': 'Personal Details',
      'Driver\'s License': 'Driver\'s License',
      'Documents': 'Documents',
      'Preferences': 'Preferences',
      'Language': 'Language',
      'English': 'English',
      'Hindi': 'Hindi',
      'Marathi': 'Marathi',
      'Introduction': 'Introduction',
      'Welcome to Metersay Driver. These Terms & Conditions govern your use of our platform. By using the app, you agree to comply with and be bound by these terms.': 'Welcome to Metersay Driver. These Terms & Conditions govern your use of our platform. By using the app, you agree to comply with and be bound by these terms.',
      'Driver Responsibilities': 'Driver Responsibilities',
      'Drivers must follow all traffic rules and regulations.': 'Drivers must follow all traffic rules and regulations.',
      'You are responsible for providing accurate information and maintaining professional behavior at all times.': 'You are responsible for providing accurate information and maintaining professional behavior at all times.',
      'Ratings & Feedback': 'Ratings & Feedback',
      'Driver performance may be monitored through user feedback.': 'Driver performance may be monitored through user feedback.',
      'Cancellation Policy': 'Cancellation Policy',
      'Unnecessary cancellation of rides is not allowed.': 'Unnecessary cancellation of rides is not allowed.',
      'Repeated cancellations may affect your account status and earnings.': 'Repeated cancellations may affect your account status and earnings.',
      'Account Suspension': 'Account Suspension',
      'Violation of any of these terms may result in temporary or permanent suspension of your account without prior notice.': 'Violation of any of these terms may result in temporary or permanent suspension of your account without prior notice.',
      'Fare Policy': 'Fare Policy',
      'All rides must follow meter-based pricing only.': 'All rides must follow meter-based pricing only.',
      'Overcharging is strictly prohibited.': 'Overcharging is strictly prohibited.',
      'Privacy Policy': 'Privacy Policy',
      'We respect your privacy and are committed to protecting your personal data in accordance with our Privacy Policy.': 'We respect your privacy and are committed to protecting your personal data in accordance with our Privacy Policy.',
      'Accept & Continue': 'Accept & Continue',
      'Verify OTP': 'Verify OTP',
      'Enter OTP': 'Enter OTP',
      'Resend': 'Resend',
      'Enter your 6 digit code sent to your registered phone number.': 'Enter your 6 digit code sent to your registered phone number.',
      'Account Created Successfully': 'Account Created Successfully',
      'Name': 'Name',
      'Enter Name': 'Enter Name',
      'Phone Number': 'Phone Number',
      'Enter Phone Number': 'Enter Phone Number',
      'Date of Birth': 'Date of Birth',
      'Gender': 'Gender',
      'Male': 'Male',
      'Female': 'Female',
      'Aadhaar Card Number': 'Aadhaar Card Number',
      'Authenticate Aadhaar Card': 'Authenticate Aadhaar Card',
      'Driving License': 'Driving License',
      'Vehicle Type': 'Vehicle Type',
      'Vehicle Photo': 'Vehicle Photo',
      'Photo of your Rickshaw': 'Photo of your Rickshaw',
      'Profile Photo (Selfie)': 'Profile Photo (Selfie)',
      'Batch Number': 'Batch Number',
      '(optional)':'(optional)',
      'Open Camera App': 'Open Camera App',
      'Take front and back picture': 'Take front and back picture',
      'Upload Minimum 4 Pictures': 'Upload Minimum 4 Pictures',
      'Take a clear picture of yourself': 'Take a clear picture of yourself',
      'Set Password': 'Set Password',
      'Enter Password': 'Enter Password',
      'Password must contain:': 'Password must contain:',
      'At least 8 characters': 'At least 8 characters',
      'One uppercase letter': 'One uppercase letter',
      'One lowercase letter': 'One lowercase letter',
      'One number or special character': 'One number or special character',
      'Do you have a criminal record?': 'Do you have a criminal record?',
      'Yes': 'Yes',
      'No': 'No',
      'I have read and agree to the Terms & Conditions and Privacy Policy.': 'I have read and agree to the Terms & Conditions and Privacy Policy.',
      'I agree to the Terms & Conditions': 'I agree to the Terms & Conditions',
      'Submit': 'Submit',
      'Next': 'Next',
      'Verify': 'Verify',
      'APNA METER, APNI KAMAI!': 'APNA METER, APNI KAMAI!',
      'Login': 'Login',
      'Create Account': 'Create Account',
      'Forgot Password': 'Forgot Password',
      'Remember Me': 'Remember Me',
      'Help & Support': 'Help & Support',
      'About Us': 'About Us',
      'Logout': 'Logout',
      'App Version 1.0.0': 'App Version 1.0.0',
      'Only female customers can book female driven rickshaws.': 'Only female customers can book female driven rickshaws.',
      'Camera app opens, only live pictures allowed, no uploading from files.': 'Camera app opens, only live pictures allowed, no uploading from files.',
      'Link the words \'Terms & Conditions\'; it will open in a new window.': 'Link the words \'Terms & Conditions\'; it will open in a new window.',
      'Driver App': 'Driver App',
      'Hello, Rakesh': 'Hello, Rakesh',
      'Welcome!': 'Welcome!',
      'Driver Dashboard': 'Driver Dashboard',
      'Dashboard':'Dashboard',
      'New Ride Request': 'New Ride Request',
      'My Trips': 'My Trips',
      'My Profile': 'My Profile',
      'You are Online': 'You are Online',
      'Online': 'Online',
      'Go Online': 'Go Online',
      'Online Time': 'Online Time',
      'Today': 'Today',
      'Weekly': 'Weekly',
      'Monthly': 'Monthly',
      'Subscribe below to get rides': 'Subscribe below to get rides',
      'Notifications': 'Notifications',
      'Please upload the original documents to start driving.':'Please upload the original documents to start driving.',
      'Ensure your documents are valid and up to date.': 'Ensure your documents are valid and up to date.',
      'Stay updated with your latest activity and important alerts.': 'Stay updated with your latest activity and important alerts.',
      'Your privacy is important to us.': 'Your privacy is important to us.',
      'This policy explains how we collect, use and protect your personal information.': 'This policy explains how we collect, use and protect your personal information.',
      'Mark all as read': 'Mark all as read',
      'Payment Received': 'Payment Received',
      'You have received ₹584 for trip to MG Road, Pune.': 'You have received ₹584 for trip to MG Road, Pune.',
      'Information We Collect': 'Information We Collect',
      'We collect personal information that you provide to us, such as your name, phone number, email address and location when you use our services.': 'We collect personal information that you provide to us, such as your name, phone number, email address and location when you use our services.',
      'How We Use Your Information': 'How We Use Your Information',
      'We use your information to provide, maintain and improve our services, process transactions, communicate with you and ensure safety and security.': 'We use your information to provide, maintain and improve our services, process transactions, communicate with you and ensure safety and security.',
      'Information Sharing': 'Information Sharing',
      'We do not sell your personal data.': 'We do not sell your personal data.',
      'We may share your information with trusted service providers only to deliver our services and comply with legal obligations.': 'We may share your information with trusted service providers only to deliver our services and comply with legal obligations.',
      'Data Security': 'Data Security',
      'We implement industry-standard security measures to protect your data from unauthorized access, misuse or disclosure.': 'We implement industry-standard security measures to protect your data from unauthorized access, misuse or disclosure.',
      'Your Choices': 'Your Choices',
      'You can update your information, manage your preferences or delete your account at any time through the app settings.': 'You can update your information, manage your preferences or delete your account at any time through the app settings.',
      'Questions or Concerns?': 'Questions or Concerns?',
      'Contact our support team at support@metersay.com': 'Contact our support team at support@metersay.com',
      'Who We Are': 'Who We Are',
      'Metersay is a technology-driven platform connecting riders with professional drivers for safe, reliable and affordable journeys.': 'Metersay is a technology-driven platform connecting riders with professional drivers for safe, reliable and affordable journeys.',
      'Our Mission': 'Our Mission',
      'To make every ride convenient, comfortable and accessible while creating opportunities for drivers to earn and grow.': 'To make every ride convenient, comfortable and accessible while creating opportunities for drivers to earn and grow.',
      'Our Vision': 'Our Vision',
      'To become the most trusted mobility platform that drives positive change in the way people and cities move.': 'To become the most trusted mobility platform that drives positive change in the way people and cities move.',
      'Our Values': 'Our Values',
      'We prioritize the safety of our riders and drivers.': 'We prioritize the safety of our riders and drivers.',
      'We believe in transparency and honest service.': 'We believe in transparency and honest service.',
      'Our customers are at the heart of everything we do.': 'Our customers are at the heart of everything we do.',
      'Edit Profile': 'Edit Profile',
      'Tap to change profile photo': 'Tap to change profile photo',
      'Full Name': 'Full Name',
      'Unique ID': 'Unique ID',
      'Address': 'Address',
      'Save Changes': 'Save Changes',
      'Cancel': 'Cancel',
      'Change Password': 'Change Password',
      'Current Password': 'Current Password',
      'New Password': 'New Password',
      'Update Password': 'Update Password',
      'Select Your Preferred Language': 'Select Your Preferred Language',
      'Choose the language you want to use in the app.': 'Choose the language you want to use in the app.',
      'Document Expiring Soon': 'Document Expiring Soon',
      'Your Driving License will expire on 12 May 2025.': 'Your Driving License will expire on 12 May 2025.',
      'Special Offer': 'Special Offer',
      'Complete 20 rides this week and get extra ₹300 bonus.': 'Complete 20 rides this week and get extra ₹300 bonus.',
      'Account Verified': 'Account Verified',
      'Congratulations! Your account has been successfully verified.': 'Congratulations! Your account has been successfully verified.',
      'Keep your documents updated.': 'Keep your documents updated.',
      'Expired documents may affect your ride requests.': 'Expired documents may affect your ride requests.',
      'Enable Push Notifications': 'Enable Push Notifications',
      'Get real-time updates and never miss important alerts.': 'Get real-time updates and never miss important alerts.',
      'Update Now': 'Update Now',
      'Total Trips': 'Total Trips',
      'Total Distance': 'Total Distance',
      'Todays Rides': 'Todays Rides',
      'Rides Completed': 'Rides Completed',
      'Ride Request': 'Ride Request',
      'Swipe to Accept': 'Swipe to Accept',
      'Accept Ride': 'Accept Ride',
      'Swipe right to accept rides': 'Swipe right to accept rides',
      'Reject': 'Reject',
      'Previous Trips': 'Previous Trips',
      'Completed': 'Completed',
      'Customer': 'Customer',
      'Distance': 'Distance',
      'Meter Based': 'Meter Based',
      'DL Number': 'DL Number',
      'Vehicle Registration': 'Vehicle Registration',
      'Vehicle Number': 'Vehicle Number',
      'Aadhaar Card': 'Aadhaar Card',
      'Upload front side of your driving license.': 'Upload front side of your driving license.',
      'Upload front side of your RC.': 'Upload front side of your RC.',
      'Upload front side of your rickshaw.': 'Upload front side of your rickshaw.',
      'Upload front side of your Aadhaar.': 'Upload front side of your Aadhaar.',
      'Upload front side of your PAN.': 'Upload front side of your PAN.',
      'Verified': 'Verified',
      'Chat With Us': 'Chat With Us',
      'Welcome to Metersay Support': 'Welcome to Metersay Support',
      'How can we help you today?': 'How can we help you today?',
      'Support Assistant': 'Support Assistant',
      'Type your message...': 'Type your message...',
      'Account & Profile Help': 'Account & Profile Help',
      'Ride Related Issues': 'Ride Related Issues',
      'Promotions & Offers': 'Promotions & Offers',
      'Find solutions for issues related to your account and profile.': 'Find solutions for issues related to your account and profile.',
      'We\'re here to help you with any ride related issues.': 'We\'re here to help you with any ride related issues.',
      'Find answers to all your questions related to promotions and offers.': 'Find answers to all your questions related to promotions and offers.',
      'Common Account Issues': 'Common Account Issues',
      'Login Issues': 'Login Issues',
      'Mobile Number Update': 'Mobile Number Update',
      'Email Address Update': 'Email Address Update',
      'Profile Information': 'Profile Information',
      'Account Deactivation': 'Account Deactivation',
      'Common Ride Issues': 'Common Ride Issues',
      'Wrong Pickup or Drop Location': 'Wrong Pickup or Drop Location',
      'Trip Cancelled by User': 'Trip Cancelled by User',
      'Trip Duration or Distance': 'Trip Duration or Distance',
      'Fare or Price Issues': 'Fare or Price Issues',
      'Route Related Issues': 'Route Related Issues',
      'Common Promotions & Offers Issues': 'Common Promotions & Offers Issues',
      'Promo Code Not Working': 'Promo Code Not Working',
      'Offer Not Received': 'Offer Not Received',
      'Offer Validity & Expiry': 'Offer Validity & Expiry',
      'Missed Bonus or Incentive': 'Missed Bonus or Incentive',
      'Incorrect Bonus Amount': 'Incorrect Bonus Amount',
      'Still Need Help?': 'Still Need Help?',
      'Our support team is available 24/7 to assist you.': 'Our support team is available 24/7 to assist you.',
      'Chat with Us': 'Chat with Us',
      'Email Us': 'Email Us',
      'support@metersay.com': 'support@metersay.com',
      'Unable to Login': 'Unable to Login',
      'I can\'t login to my account.': 'I can\'t login to my account.',
      'I forgot my password.': 'I forgot my password.',
      'Didn\'t Receive OTP': 'Didn\'t Receive OTP',
      'I didn\'t receive the OTP on my mobile number.': 'I didn\'t receive the OTP on my mobile number.',
      'OTP Not Working': 'OTP Not Working',
      'The OTP I received isn\'t working.': 'The OTP I received isn\'t working.',
      'Account Locked': 'Account Locked',
      'My account has been locked.': 'My account has been locked.',
      'How to Update Your Mobile Number': 'How to Update Your Mobile Number',
      'Step 1: Go to Profile > Account Settings.': 'Step 1: Go to Profile > Account Settings.',
      'Step 2: Tap on Mobile Number.': 'Step 2: Tap on Mobile Number.',
      'Step 3: Enter your new mobile number.': 'Step 3: Enter your new mobile number.',
      'Step 4: Verify the new number with OTP.': 'Step 4: Verify the new number with OTP.',
      'Step 5: Your mobile number will be updated successfully.': 'Step 5: Your mobile number will be updated successfully.',
      'How to Update Your Email Address': 'How to Update Your Email Address',
      'Step 2: Tap on Email Address.': 'Step 2: Tap on Email Address.',
      'Step 3: Enter your new email address.': 'Step 3: Enter your new email address.',
      'Step 4: Verify the email by clicking on the link.': 'Step 4: Verify the email by clicking on the link.',
      'Step 5: Your email address will be updated successfully.': 'Step 5: Your email address will be updated successfully.',
      'How to Deactivate Your Account': 'How to Deactivate Your Account',
      'Step 2: Tap on Account Deactivation.': 'Step 2: Tap on Account Deactivation.',
      'Step 3: Select a reason for deactivation.': 'Step 3: Select a reason for deactivation.',
      'Step 4: Review important information before proceeding.': 'Step 4: Review important information before proceeding.',
      'Step 5: Confirm your request to deactivate your account.': 'Step 5: Confirm your request to deactivate your account.',
    },
    'हिंदी': {
      'Continue':'जारी रखना',
      'Transparent Pricing, No Hidden fees or Commission':'पारदर्शी कीमतें, कोई छिपी हुई फीस या कमीशन नहीं',
      'SUBSCRIPTION':'सब्सक्रिप्शन',
      'Vehicle RC':'वाहन का RC',
      'Driver Login': 'ड्राइवर लॉगिन',
      'Payments': 'भुगतान',
      'Manage Your Payments': 'अपने भुगतान प्रबंधित करें',
      'View payment methods and transaction history.': 'भुगतान के तरीके और लेनदेन का इतिहास देखें।',
      'Payment Methods': 'भुगतान के तरीके',
      'Google Pay': 'गूगल पे  (Google Pay)',
      'PhonePe': 'फोनपे  (PhonePe)',
      'Bank Transfer': 'बैंक ट्रांसफर',
      'Wallet': 'वॉलेट',
      'Recent Transactions': 'हालिया लेनदेन',
      'Wallet Balance Added': 'वॉलेट बैलेंस जोड़ा गया',
      'Payout to Metersay': 'Metersay को भुगतान',
      'Secure Payments': 'भुगतान सुरक्षित करें',
      'Your payments are encrypted and secured with top-level security.': 'आपके भुगतान एन्क्रिप्ट और उच्च स्तरीय सुरक्षा द्वारा सुरक्षित किए गए हैं।',
      'Learn More': 'अधिक जानें',
      'Registration': 'पंजीकरण',
      'Welcome Back!!': 'आपका फिर से स्वागत है!!',
      'Upload Documents': 'दस्तावेज़ अपलोड करें',
      'Details': 'विवरण',
      'Settings': 'सेटिंग्स',
      'Terms and Conditions': 'नियम एवं शर्तें',
      'Account': 'खाता',
      'Last Updated: 27 April 2026': 'अंतिम अपडेट: 27 अप्रैल 2026',
      'Personal Details': 'व्यक्तिगत जानकारी',
      'Driver\'s License': 'ड्राइविंग लाइसेंस',
      'Documents': 'दस्तावेज़',
      'Preferences': 'प्राथमिकताएं',
      'Language': 'भाषा',
      'English': 'अंग्रेजी',
      'Hindi': 'हिंदी',
      'Marathi': 'मराठी',
      'Introduction': 'प्रस्तावना',
      'Welcome to Metersay Driver. These Terms & Conditions govern your use of our platform. By using the app, you agree to comply with and be bound by these terms.': 'Metersay Driver में आपका स्वागत है। ये नियम और शर्तें हमारे प्लेटफॉर्म के आपके उपयोग को नियंत्रित करते हैं। ऐप का उपयोग करके, आप इन शर्तों का पालन करने और उनसे बाध्य होने के लिए सहमत होते हैं।',
      'Driver Responsibilities': 'ड्राइवर की जिम्मेदारियां',
      'Drivers must follow all traffic rules and regulations.': 'ड्राइवरों को सभी यातायात नियमों और विनियमों का पालन करना होगा।',
      'You are responsible for providing accurate information and maintaining professional behavior at all times.': 'आप हर समय सटीक जानकारी प्रदान करने और व्यावसायिक व्यवहार बनाए रखने के लिए जिम्मेदार हैं।',
      'Ratings & Feedback': 'रेटिंग्स और फीड़बैक',
      'Driver performance may be monitored through user feedback.': 'उपयोगकर्ता के फीड़बैक द्वारा ड्राइवर के प्रदर्शन की निगरानी की जा सकती है।',
      'Cancellation Policy': 'रद्दीकरण नीति',
      'Unnecessary cancellation of rides is not allowed.': 'राइड्स के अनावश्यक रद्दीकरण की अनुमति नहीं है।',
      'Repeated cancellations may affect your account status and earnings.': 'बार-बार राइड रद्दीकरण से आपके खाते की स्थिति और कमाई प्रभावित हो सकती है।',
      'Account Suspension': 'खाता निलंबन',
      'Violation of any of these terms may result in temporary or permanent suspension of your account without prior notice.': 'इनमें से किसी भी शर्त का उल्लंघन करने पर बिना किसी पूर्व सूचना के आपका खाता अस्थायी या स्थायी रूप से निलंबित किया जा सकता है।',
      'Fare Policy': 'किराया नीति',
      'All rides must follow meter-based pricing only.': 'सभी राइड्स में केवल मीटर-आधारित मूल्य निर्धारण का पालन किया जाना चाहिए।',
      'Overcharging is strictly prohibited.': 'अधिक किराया वसूल करना सख्त रूप से वर्जित है।',
      'Privacy Policy': 'गोपनीयता नीति',
      'We respect your privacy and are committed to protecting your personal data in accordance with our Privacy Policy.': 'हम आपकी गोपनीयता का सम्मान करते हैं और अपनी गोपनीयता नीति के अनुसार आपके व्यक्तिगत डेटा की सुरक्षा के लिए प्रतिबद्ध हैं।',
      'Accept & Continue': 'स्वीकारें और जारी रखें',
      'Verify OTP': 'ओटीपी (OTP) सत्यापित करें',
      'Enter OTP': 'ओटीपी (OTP) दर्ज करें',
      'Resend': 'पुनः भेजें',
      'Enter your 6 digit code sent to your registered phone number.': 'अपने पंजीकृत फ़ोन नंबर पर भेजा गया 6 अंकों का कोड दर्ज करें।',
      'Account Created Successfully': 'खाता सफलतापूर्वक बनाया गया',
      'Name': 'नाम',
      'Enter Name': 'नाम दर्ज करें',
      'Phone Number': 'फ़ोन नंबर',
      'Enter Phone Number': 'फ़ोन नंबर दर्ज करें',
      'Date of Birth': 'जन्म तिथि',
      'Gender': 'लिंग',
      'Male': 'पुरुष',
      'Female': 'महिला',
      'Aadhaar Card Number': 'आधार कार्ड नंबर',
      'Authenticate Aadhaar Card': 'आधार कार्ड प्रमाणित करें',
      'Driving License': 'ड्राइविंग लाइसेंस',
      'Vehicle Type': 'वाहन का प्रकार',
      'Vehicle Photo': 'वाहन की फोटो',
      'Photo of your Rickshaw': 'आपके रिक्शा की फोटो',
      'Profile Photo (Selfie)': 'प्रोफ़ाइल फ़ोटो (सेल्फ़ी)',
      'Batch Number': 'बैच नंबर',
      '(optional)':'(वैकल्पिक)',
      'Open Camera App': 'कैमरा ऐप खोलें',
      'Take front and back picture': 'आगे और पीछे की तस्वीर लें',
      'Upload Minimum 4 Pictures': 'न्यूनतम 4 तस्वीरें अपलोड करें',
      'Take a clear picture of yourself': 'अपनी एक स्पष्ट तस्वीर लें',
      'Set Password': 'पासवर्ड सेट करें',
      'Enter Password': 'पासवर्ड दर्ज करें',
      'Password must contain:': 'पासवर्ड में निम्न होना चाहिए:',
      'At least 8 characters': 'कम से कम 8 अक्षर',
      'One uppercase letter': 'एक बड़ा अक्षर (Uppercase)',
      'One lowercase letter': 'एक छोटा अक्षर (Lowercase)',
      'One number or special character': 'एक संख्या या विशेष वर्ण',
      'Do you have a criminal record?': 'क्या आपका कोई आपराधिक रिकॉर्ड है?',
      'Yes': 'हाँ',
      'No': 'नहीं',
      'I have read and agree to the Terms & Conditions and Privacy Policy.': 'मैंने नियम व शर्तें और गोपनीयता नीति पढ़ ली है और मैं उनसे सहमत हूँ।',
      'I agree to the Terms & Conditions': 'मैं नियम और शर्तों से सहमत हूँ',
      'Submit': 'सबमिट करें',
      'Next': 'अगला',
      'Verify': 'सत्यापित करें',
      'APNA METER, APNI KAMAI!': 'अपना मीटर, अपनी कमाई!',
      'Login': 'लॉगिन',
      'Create Account': 'खाता बनाएं',
      'Forgot Password': 'पासवर्ड भूल गए',
      'Remember Me': 'मेरी जानकारी याद रखें (Remember Me)',
      'Help & Support': 'सहायता और समर्थन',
      'About Us': 'हमारे बारे में',
      'Logout': 'लॉगआउट',
      'App Version 1.0.0': 'ऐप संस्करण 1.0.0',
      'Only female customers can book female driven rickshaws.': 'केवल महिला ग्राहक ही महिला चालित रिक्शा बुक कर सकती हैं।',
      'Camera app opens, only live pictures allowed, no uploading from files.': 'कैमरा ऐप खुलता है, केवल लाइव तस्वीरों की अनुमति है, फाइलों से अपलोड कर नहीं सकते।',
      'Link the words \'Terms & Conditions\'; it will open in a new window.': '\'नियम और शर्तें\' शब्दों को लिंक करें; यह एक नई विंडो में खुलेगा।',
      'Driver App': 'ड्राइवर ऐप (Driver App)',
      'Hello, Rakesh': 'नमस्ते, राकेश',
      'Welcome!': 'आपका स्वागत है!',
      'Driver Dashboard': 'ड्राइवर डैशबोर्ड',
      'Dashboard':'डैशबोर्ड',
      'New Ride Request': 'नई राइड का अनुरोध',
      'My Trips': 'मेरी यात्राएं',
      'My Profile': 'मेरी प्रोफ़ाइल',
      'You are Online': 'आप ऑनलाइन हैं',
      'Online': 'ऑनलाइन',
      'Go Online': 'ऑनलाइन जाएँ',
      'Online Time': 'ऑनलाइन समय',
      'Today': 'आज',
      'Weekly': 'साप्ताहिक',
      'Monthly': 'मासिक',
      'Subscribe below to get rides': 'राइड्स प्राप्त करने के लिए नीचे सदस्यता लें',
      'Notifications': 'सूचनाएं',
      'Please upload the original documents to start driving.':'ड्राइविंग शुरू करने के लिए कृपया ओरिजिनल डॉक्यूमेंट्स अपलोड करें।',
      'Ensure your documents are valid and up to date.': 'सुनिश्चित करें कि आपके दस्तावेज़ वैध और अद्यतित (अप-टू-डेट) हैं या नहीं।',
      'Stay updated with your latest activity and important alerts.': 'अपनी नवीनतम गतिविधि और महत्वपूर्ण अलर्ट के साथ अपडेट रहें।',
      'Your privacy is important to us.': 'आपकी गोपनीयता हमारे लिए महत्वपूर्ण है।',
      'This policy explains how we collect, use and protect your personal information.': 'यह नीति बताती है कि हम आपकी व्यक्तिगत जानकारी को कैसे एकत्र, उपयोग और सुरक्षित करते हैं।',
      'Mark all as read': 'सभी को पढ़ा हुआ चिह्नित करें',
      'Payment Received': 'भुगतान प्राप्त हुआ',
      'You have received ₹584 for trip to MG Road, Pune.': 'आपको एमजी रोड, पुणे की यात्रा के लिए ₹584 प्राप्त हुए हैं।',
      'Information We Collect': 'हमारे द्वारा एकत्रित की जानेवाली जानकारी जानकारी',
      'We collect personal information that you provide to us, such as your name, phone number, email address and location when you use our services.': 'जब आप हमारी सेवाओं का उपयोग करते हैं, तब हम आपके द्वारा आपका नाम, फ़ोन नंबर, ईमेल पता और स्थान जैसी प्रदान की जाने वाली व्यक्तिगत जानकारी एकत्रित करते हैं।',
      'How We Use Your Information': 'हम आपकी जानकारी का उपयोग कैसे करते हैं',
      'We use your information to provide, maintain and improve our services, process transactions, communicate with you and ensure safety and security.': 'हम आपकी जानकारी का उपयोग अपनी सेवाओं को प्रदान करने, बनाए रखने और सुधारने, लेनदेन को संसाधित करने, आपसे संवाद करने और सुरक्षा व संरक्षा सुनिश्चित करने के लिए करते हैं।',
      'Information Sharing': 'जानकारी साझा करना',
      'We do not sell your personal data.': 'हम आपका व्यक्तिगत डेटा बेचते नहीं हैं।',
      'We may share your information with trusted service providers only to deliver our services and comply with legal obligations.': 'हम आपकी जानकारी केवल अपनी सेवाएं देने और कानूनी दायित्वों का पालन करने के लिए विश्वसनीय सेवा प्रदाताओं के साथ साझा कर सकते हैं।',
      'Data Security': 'डेटा सुरक्षा',
      'We implement industry-standard security measures to protect your data from unauthorized access, misuse or disclosure.': 'हम आपके डेटा को अनधिकृत पहुंच, दुरुपयोग या प्रकटीकरण से बचाने के लिए उद्योग-मानक सुरक्षा उपाय लागू करते हैं।',
      'Your Choices': 'आपके विकल्प',
      'You can update your information, manage your preferences or delete your account at any time through the app settings.': 'आप ऐप सेटिंग्स द्वारा किसी भी समय अपनी जानकारी अपडेट कर सकते हैं, अपनी प्राथमिकताओं को प्रबंधित कर सकते हैं या अपना खाता हटा सकते हैं।',
      'Questions or Concerns?': 'प्रश्न या चिंताएँ?',
      'Contact our support team at support@metersay.com': 'हमारी सहायता टीम से support@metersay.com पर संपर्क करें',
      'Who We Are': 'हम कौन हैं',
      'Metersay is a technology-driven platform connecting riders with professional drivers for safe, reliable and affordable journeys.': 'Metersay एक तकनीक-संचालित प्लेटफॉर्म है जो सुरक्षित, विश्वसनीय और सुलभ यात्राओं के लिए यात्रियों को पेशेवर ड्राइवरों से जोड़ता है।',
      'Our Mission': 'हमारा उद्देश्य',
      'To make every ride convenient, comfortable and accessible while creating opportunities for drivers to earn and grow.': 'ड्राइवरों के लिए कमाने और आगे बढ़ने के अवसर पैदा करते हुए हर राइड को सुविधाजनक, आरामदायक और सुलभ बनाना।',
      'Our Vision': 'हमारा दृष्टिकोण',
      'To become the most trusted mobility platform that drives positive change in the way people and cities move.': 'सबसे भरोसेमंद गतिशीलता (मोबिलिटी) प्लेटफॉर्म बनना जो लोगों और शहरों के हलनचलन में सकारात्मक बदलाव लाए।',
      'Our Values': 'हमारे मूल्य',
      'We prioritize the safety of our riders and drivers.': 'हम अपने यात्रियों और ड्राइवरों की सुरक्षा को प्राथमिकता देते हैं।',
      'We believe in transparency and honest service.': 'हम पारदर्शिता और ईमानदार सेवा में विश्वास करते हैं।',
      'Our customers are at the heart of everything we do.': 'हमारे ग्राहक हमारे हर काम के केंद्र में हैं।',
      'Edit Profile': 'प्रोफ़ाइल संपादित करें',
      'Tap to change profile photo': 'प्रोफ़ाइल फोटो बदलने के लिए टैप करें',
      'Full Name': 'पूरा नाम',
      'Unique ID': 'विशिष्ट आईडी (Unique ID)',
      'Address': 'पता',
      'Save Changes': 'बदलावों को सहेजें',
      'Cancel': 'रद्द करें',
      'Change Password': 'पासवर्ड बदलें',
      'Current Password': 'वर्तमान पासवर्ड',
      'New Password': 'नया पासवर्ड',
      'Update Password': 'पासवर्ड अपडेट करें',
      'Select Your Preferred Language': 'अपनी पसंदीदा भाषा चुनें',
      'Choose the language you want to use in the app.': 'वह भाषा चुनें जिसका आप ऐप में उपयोग करना चाहते हैं।',
      'Document Expiring Soon': 'दस्तावेज़ जल्द ही समाप्त होने वाला है',
      'Your Driving License will expire on 12 May 2025.': 'आपका ड्राइविंग लाइसेंस 12 मई 2025 को समाप्त हो जाएगा।',
      'Special Offer': 'विशेष प्रस्ताव (ऑफ़र)',
      'Complete 20 rides this week and get extra ₹300 bonus.': 'इस सप्ताह 20 राइड्स पूरी करें और अतिरिक्त ₹300 बोनस पाएं।',
      'Account Verified': 'खाता सत्यापित हो गया',
      'Congratulations! Your account has been successfully verified.': 'बधाई हो! आपका खाता सफलतापूर्वक सत्यापित कर दिया गया है।',
      'Keep your documents updated.': 'अपने दस्तावेज़ों को अपडेट रखें।',
      'Expired documents may affect your ride requests.': 'समय-सीमा समाप्त (Expired) दस्तावेज़ आपकी राइड के अनुरोधों को प्रभावित कर सकते हैं।',
      'Enable Push Notifications': 'पुश नोटिफिकेशन सक्षम करें',
      'Get real-time updates and never miss important alerts.': 'रीयल-टाइम अपडेट प्राप्त करें और महत्वपूर्ण अलर्ट कभी न चूकें।',
      'Update Now': 'अभी अपडेट करें',
      'Total Trips': 'कुल यात्राएं',
      'Total Distance': 'कुल दूरी',
      'Todays Rides': 'आज की राइड्स',
      'Rides Completed': 'पूरी की गई राइड्स',
      'Ride Request': 'राइड का अनुरोध',
      'Swipe to Accept': 'स्वीकार करने के लिए स्वाइप करें',
      'Accept Ride': 'राइड स्वीकारें',
      'Swipe right to accept rides': 'राइड्स स्वीकार करने के लिए दाईं ओर स्वाइप करें',
      'Reject': 'अस्वीकार करें',
      'Previous Trips': 'पिछली यात्राएं',
      'Completed': 'पूरा हुआ',
      'Customer': 'ग्राहक',
      'Distance': 'दूरी',
      'Meter Based': 'मीटर आधारित',
      'DL Number': 'DL नंबर',
      'Vehicle Registration': 'वाहन पंजीकरण',
      'Vehicle Number': 'वाहन नंबर',
      'Aadhaar Card': 'आधार कार्ड',
      'Upload front side of your driving license.': 'अपने ड्राइविंग लाइसेंस का अगला भाग अपलोड करें।',
      'Upload front side of your RC.': 'अपनी आरसी (RC) का अगला भाग अपलोड करें।',
      'Upload front side of your rickshaw.': 'अपने रिक्शे का अगला भाग अपलोड करें।',
      'Upload front side of your Aadhaar.': 'अपने आधार का अगला भाग अपलोड करें।',
      'Upload front side of your PAN.': 'अपने पैन (PAN) का अगला भाग अपलोड करें।',
      'Verified': 'सत्यापित किए गए',
      'Chat With Us': 'हमसे चैट करें',
      'Welcome to Metersay Support': 'Metersay सहायता में आपका स्वागत है',
      'How can we help you today?': 'आज हम आपकी क्या सहायता कर सकते हैं?',
      'Support Assistant': 'सहायता सहायक (सपोर्ट असिस्टेंट)',
      'Type your message...': 'अपना संदेश टाइप करें...',
      'Account & Profile Help': 'खाता और प्रोफ़ाइल सहायता',
      'Ride Related Issues': 'राइड से संबंधित समस्याएं',
      'Promotions & Offers': 'प्रचार और ऑफ़र',
      'Find solutions for issues related to your account and profile.': 'अपने खाते और प्रोफ़ाइल से संबंधित समस्याओं के समाधान खोजें।',
      'We\'re here to help you with any ride related issues.': 'राइड से संबंधित किसी भी समस्या में हम आपकी सहायता करने के लिए हम यहाँ मौजूद हैं।',
      'Find answers to all your questions related to promotions and offers.': 'प्रचार और ऑफ़र से संबंधित अपने सभी प्रश्नों के उत्तर खोजें।',
      'Common Account Issues': 'खाता संबंधित आम समस्याएँ',
      'Login Issues': 'लॉगिन समस्याएँ',
      'Mobile Number Update': 'मोबाइल नंबर अपडेट',
      'Email Address Update': 'ईमेल पता अपडेट',
      'Profile Information': 'प्रोफ़ाइल जानकारी',
      'Account Deactivation': 'खाता निष्क्रिय करना',
      'Common Ride Issues': 'राइड संबंधित आम समस्याएँ',
      'Wrong Pickup or Drop Location': 'गलत पिकअप या ड्रॉप लोकेशन',
      'Trip Cancelled by User': 'उपयोगकर्ता द्वारा यात्रा रद्द करना',
      'Trip Duration or Distance': 'यात्रा की अवधि या दूरी',
      'Fare or Price Issues': 'किराए या मूल्य की समस्याएं',
      'Route Related Issues': 'मार्ग से संबंधित समस्याएं',
      'Common Promotions & Offers Issues': 'प्रचार और ऑफ़र संबंधित आम समस्याएँ',
      'Promo Code Not Working': 'प्रोमो कोड काम नहीं कर रहा है',
      'Offer Not Received': 'ऑफ़र प्राप्त नहीं हुई',
      'Offer Validity & Expiry': 'ऑफ़र की वैधता और समाप्ति',
      'Missed Bonus or Incentive': 'छूटा हुआ बोनस या प्रोत्साहन',
      'Incorrect Bonus Amount': 'गलत बोनस राशि',
      'Still Need Help?': 'क्या अब भी सहायता चाहिए?',
      'Our support team is available 24/7 to assist you.': 'हमारी सहायता टीम आपकी सहायता के लिए 24/7 उपलब्ध है।',
      'Chat with Us': 'हमसे चैट करें',
      'Email Us': 'हमें ईमेल करें',
      'support@metersay.com': 'support@metersay.com',
      'Unable to Login': 'लॉगिन करने में असमर्थ',
      'I can\'t login to my account.': 'मैं अपने खाते में लॉगिन नहीं कर पा रहा हूँ।',
      'I forgot my password.': 'मैं अपना पासवर्ड भूल गया हूँ।',
      'Didn\'t Receive OTP': 'OTP प्राप्त नहीं हुआ',
      'I didn\'t receive the OTP on my mobile number.': 'मुझे मेरे मोबाइल नंबर पर OTP प्राप्त नहीं हुआ।',
      'OTP Not Working': 'OTP काम नहीं कर रहा है',
      'The OTP I received isn\'t working.': 'मुझे जो OTP मिला है वह काम नहीं कर रहा है।',
      'Account Locked': 'खाता लॉक हो गया है',
      'My account has been locked.': 'मेरा खाता लॉक कर दिया गया है।',
      'How to Update Your Mobile Number': 'अपना मोबाइल नंबर कैसे अपडेट करें',
      'Step 1: Go to Profile > Account Settings.': 'चरण 1: प्रोफ़ाइल > खाता सेटिंग्स पर जाएं।',
      'Step 2: Tap on Mobile Number.': 'चरण 2: मोबाइल नंबर पर टैप करें।',
      'Step 3: Enter your new mobile number.': 'चरण 3: अपना नया मोबाइल नंबर दर्ज करें।',
      'Step 4: Verify the new number with OTP.': 'चरण 4: OTP के साथ नए नंबर को सत्यापित करें।',
      'Step 5: Your mobile number will be updated successfully.': 'चरण 5: आपका मोबाइल नंबर सफलतापूर्वक अपडेट हो जाएगा।',
      'How to Update Your Email Address': 'अपना ईमेल पता कैसे अपडेट करें',
      'Step 2: Tap on Email Address.': 'चरण 2: ईमेल पते पर टैप करें।',
      'Step 3: Enter your new email address.': 'चरण 3: अपना नया ईमेल पता दर्ज करें।',
      'Step 4: Verify the email by clicking on the link.': 'चरण 4: लिंक पर क्लिक करके ईमेल सत्यापित करें।',
      'Step 5: Your email address will be updated successfully.': 'चरण 5: आपका ईमेल पता सफलतापूर्वक अपडेट हो जाएगा।',
      'How to Deactivate Your Account': 'अपना खाता कैसे निष्क्रिय करें',
      'Step 2: Tap on Account Deactivation.': 'चरण 2: खाता निष्क्रिय करें पर टैप करें।',
      'Step 3: Select a reason for deactivation.': 'चरण 3: निष्क्रिय करने का कारण चुनें।',
      'Step 4: Review important information before proceeding.': 'चरण 4: आगे बढ़ने से पहले महत्वपूर्ण जानकारी की समीक्षा करें।',
      'Step 5: Confirm your request to deactivate your account.': 'चरण 5: अपना खाता निष्क्रिय करने के अपने अनुरोध की पुष्टि करें।',
    },
    'मराठी': {
      'Continue':'पुढे चालू ठेवा',
      'Transparent Pricing, No Hidden fees or Commission':'पारदर्शक दर, कोणतेही छुपे शुल्क किंवा कमिशन नाही',
      'SUBSCRIPTION':'वर्गणी',
      'Vehicle RC':'वाहन आर.सी',
      'Driver Login': 'ड्राइवर लॉगिन',
      'Payments': 'पेमेंट्स (देयके)',
      'Manage Your Payments': 'तुमचे पेमेंट्स व्यवस्थापित करा',
      'View payment methods and transaction history.': 'पेमेंटच्या पद्धती आणि व्यवहारांचा इतिहास पहा.',
      'Payment Methods': 'पेमेंटच्या पद्धती',
      'Google Pay': 'गुगल पे  (Google Pay)',
      'PhonePe': 'फोन पे  (PhonePe)',
      'Bank Transfer': 'बँक ट्रान्सफर',
      'Wallet': 'वॉलेट',
      'Recent Transactions': 'अलीकडील व्यवहार',
      'Wallet Balance Added': 'वॉलेट शिल्लक (बॅलन्स) जोडले',
      'Payout to Metersay': 'Metersay ला पेआउट',
      'Secure Payments': 'पेमेंट्स सुरक्षित करा',
      'Your payments are encrypted and secured with top-level security.': 'तुमचे पेमेंट्स एन्क्रिप्टेड आहेत आणि उच्च-स्तरीय सुरक्षेसह सुरक्षित आहेत.',
      'Learn More': 'अधिक जाणून घ्या',
      'Registration': 'नोंदणी',
      'Welcome Back!!': 'तुमचे पुन्हा स्वागत आहे!!',
      'Upload Documents': 'कागदपत्रे अपलोड करा',
      'Details': 'तपशील',
      'Settings': 'सेटिंग्स (रचना)',
      'Terms and Conditions': 'नियम आणि अटी',
      'Account': 'खाते',
      'Last Updated: 27 April 2026': 'अंतिम अद्यतन: २७ एप्रिल २०२६',
      'Personal Details': 'वैयक्तिक माहिती',
      'Driver\'s License': 'ड्रायव्हिंग लायसन्स (चालक परवाना)',
      'Documents': 'कागदपत्रे',
      'Preferences': 'पसंतीक्रम',
      'Language': 'भाषा',
      'English': 'इंग्रजी',
      'Hindi': 'हिंदी',
      'Marathi': 'मराठी',
      'Introduction': 'प्रस्तावना',
      'Welcome to Metersay Driver. These Terms & Conditions govern your use of our platform. By using the app, you agree to comply with and be bound by these terms.': 'Metersay Driverमध्ये आपले स्वागत आहे. या नियम आणि अटी आमच्या प्लॅटफॉर्मच्या तुमच्या वापराचे नियंत्रण करतात. हे ॲप वापरून, तुम्ही या अटींचे पालन करण्यास आणि त्यांच्याशी बांधील राहण्यास सहमत आहात.',
      'Driver Responsibilities': 'चालकाची (ड्रायव्हरची) जबाबदारी',
      'Drivers must follow all traffic rules and regulations.': 'ड्रायव्हर्सनी सर्व वाहतूक नियमांचे आणि कायद्यांचे पालन केले पाहिजे.',
      'You are responsible for providing accurate information and maintaining professional behavior at all times.': 'तुम्ही नेहमी अचूक माहिती देण्यासाठी आणि व्यावसायिक वर्तन राखण्यासाठी जबाबदार आहात.',
      'Ratings & Feedback': 'रेटिंग्स आणि फीडबॅक (अभिप्राय)',
      'Driver performance may be monitored through user feedback.': 'वापरकर्त्याच्या फीडबॅकद्वारे ड्रायव्हरच्या कामगिरीवर लक्ष ठेवले जाऊ शकते.',
      'Cancellation Policy': 'रद्द करण्याचे धोरण (कॅन्शलेशन पॉलिसी)',
      'Unnecessary cancellation of rides is not allowed.': 'विनाकारण राईड्स रद्द करण्यास परवानगी नाही.',
      'Repeated cancellations may affect your account status and earnings.': 'वारंवार राईड्स रद्द केल्यास तुमच्या खात्याच्या स्थितीवर आणि कमाईवर परिणाम होऊ शकतो.',
      'Account Suspension': 'खाते निलंबन (अकाउंट सस्पेंशन)',
      'Violation of any of these terms may result in temporary or permanent suspension of your account without prior notice.': 'यापैकी कोणत्याही अटींचे उल्लंघन केल्यास पूर्वसूचनेशिवाय तुमचे खाते तात्पुरते किंवा कायमचे निलंबित केले जाऊ शकते.',
      'Fare Policy': 'भाडे धोरण (फेअर पॉलिसी)',
      'All rides must follow meter-based pricing only.': 'सर्व राईड्ससाठी फक्त मीटर-आधारित भाडे आकारणीचे पालन करणे बंधनकारक आहे.',
      'Overcharging is strictly prohibited.': 'जास्त भाडे आकारण्यास सक्त मनाई आहे.',
      'Privacy Policy': 'गोपनीयता धोरण',
      'We respect your privacy and are committed to protecting your personal data in accordance with our Privacy Policy.': 'आम्ही तुमच्या गोपनीयतेचा आदर करतो आणि आमच्या गोपनीयता धोरणानुसार तुमच्या वैयक्तिक डेटाचे संरक्षण करण्यासाठी कटिबद्ध आहोत.',
      'Accept & Continue': 'स्वीकारा आणि पुढे जा',
      'Verify OTP': 'ओटीपी (OTP) सत्यापित करा',
      'Enter OTP': 'ओटीपी (OTP) प्रविष्ट करा',
      'Resend': 'पुन्हा पाठवा',
      'Enter your 6 digit code sent to your registered phone number.': 'तुमच्या नोंदणीकृत फोन नंबरवर पाठवलेला ६ अंकी कोड प्रविष्ट करा.',
      'Account Created Successfully': 'खाते यशस्वीरित्या तयार केले गेले',
      'Name': 'नाव',
      'Enter Name': 'नाव प्रविष्ट करा',
      'Phone Number': 'फोन नंबर',
      'Enter Phone Number': 'फोन नंबर प्रविष्ट करा',
      'Date of Birth': 'जन्म तारीख',
      'Gender': 'लिंग',
      'Male': 'पुरुष',
      'Female': 'महिला',
      'Aadhaar Card Number': 'आधार कार्ड नंबर',
      'Authenticate Aadhaar Card': 'आधार कार्ड प्रमाणित करा',
      'Driving License': 'ड्रायव्हिंग लायसन्स',
      'Vehicle Type': 'वाहनाचा प्रकार',
      'Vehicle Photo': 'वाहनाचा फोटो',
      'Photo of your Rickshaw': 'तुमच्या रिक्षाचा फोटो',
      'Profile Photo (Selfie)': 'प्रोफाईल फोटो (सेल्फी)',
      'Batch Number': 'बॅच नंबर',
      '(optional)':'(पर्यायी)',
      'Open Camera App': 'कॅमेरा ॲप उघडा',
      'Take front and back picture': 'पुढचा आणि मागचा फोटो काढा',
      'Upload Minimum 4 Pictures': 'किमान ४ फोटो अपलोड करा',
      'Take a clear picture of yourself': 'स्वतःचा एक स्पष्ट फोटो काढा',
      'Set Password': 'पासवर्ड सेट करा',
      'Enter Password': 'पासवर्ड प्रविष्ट करा',
      'Password must contain:': 'पासवर्डमध्ये खालील गोष्टी असणे आवश्यक आहे:',
      'At least 8 characters': 'किमान ८ अक्षरे',
      'One uppercase letter': 'एक मोठे अक्षर (Uppercase)',
      'One lowercase letter': 'एक लहान अक्षर (Lowercase)',
      'One number or special character': 'एक अंक किंवा विशेष चिन्ह (Special Character)',
      'Do you have a criminal record?': 'तुमचा कोणताही गुन्हेगारी रेकॉर्ड आहे का?',
      'Yes': 'होय',
      'No': 'नाही',
      'I have read and agree to the Terms & Conditions and Privacy Policy.': 'मी नियम व अटी आणि गोपनीयता धोरण वाचले आहे आणि मी त्यांच्याशी सहमत आहे.',
      'I agree to the Terms & Conditions': 'मी नियम आणि अटींशी सहमत आहे',
      'Submit': 'सबमिट करा',
      'Next': 'पुढे',
      'Verify': 'सत्यापित करा',
      'APNA METER, APNI KAMAI!': 'आपला मीटर, आपली कमाई!',
      'Login': 'लॉगिन',
      'Create Account': 'खाते तयार करा',
      'Forgot Password': 'पासवर्ड विसरलात',
      'Remember Me': 'माझी माहिती लक्षात ठेवा (Remember Me)',
      'Help & Support': 'मदत आणि समर्थन',
      'About Us': 'आमच्याबद्दल',
      'Logout': 'लॉगआउट',
      'App Version 1.0.0': 'ॲप आवृत्ती १.०.०',
      'Only female customers can book female driven rickshaws.': 'केवळ महिला ग्राहकच महिला चालवत असलेल्या रिक्षा बुक करू शकतात.',
      'Camera app opens, only live pictures allowed, no uploading from files.': 'कॅमेरा ॲप उघडेल, फक्त थेट (लाइव्ह) फोटोंना परवानगी आहे, फाईल्समधून अपलोड करता येणार नाही.',
      'Link the words \'Terms & Conditions\'; it will open in a new window.': '\'नियम आणि अटी\' या शब्दांना लिंक करा; ते नवीन विंडोमध्ये उघडेल.',
      'Driver App': 'ड्रायव्हर ॲप (Driver App)',
      'Hello, Rakesh': 'हॅलो, राकेश',
      'Welcome!': 'आपले स्वागत आहे!',
      'Driver Dashboard': 'ड्रायव्हर डॅशबोर्ड',
      'Dashboard':'डॅशबोर्ड',
      'New Ride Request': 'नवीन राईडची विनंती',
      'My Trips': 'माझ्या ट्रिप्स (फेऱ्या)',
      'My Profile': 'माझी प्रोफाईल',
      'You are Online': 'तुम्ही ऑनलाईन आहात',
      'Online': 'ऑनलाईन',
      'Go Online': 'ऑनलाईन या',
      'Online Time': 'ऑनलाईन वेळ',
      'Today': 'आज',
      'Weekly': 'साप्ताहिक',
      'Monthly': 'मासिक',
      'Subscribe below to get rides': 'राईड्स मिळवण्यासाठी खाली सबस्क्राईब करा',
      'Notifications': 'नोटिफिकेशन्स (सूचना)',
      'Please upload the original documents to start driving.':'गाडी चालवण्यास सुरुवात करण्यासाठी कृपया मूळ कागदपत्रे अपलोड करा.',
      'Ensure your documents are valid and up to date.': 'तुमची कागदपत्रे वैध आणि अद्ययावत असल्याची खात्री करा.',
      'Stay updated with your latest activity and important alerts.': 'तुमच्या नवीनतम क्रियाकलापांबद्दल आणि महत्त्वाच्या सूचनांबद्दल अपडेट रहा.',
      'Your privacy is important to us.': 'तुमची गोपनीयता आमच्यासाठी महत्त्वाची आहे.',
      'This policy explains how we collect, use and protect your personal information.': 'आम्ही तुमची वैयक्तिक माहिती कशी गोळा करतो, वापरतो आणि सुरक्षित ठेवतो हे या धोरणामध्ये स्पष्ट केले आहे.',
      'Mark all as read': 'सर्व वाचलेले म्हणून चिन्हांकित करा',
      'Payment Received': 'पेमेंट मिळाले',
      'You have received ₹584 for trip to MG Road, Pune.': 'तुम्हाला एमजी रोड, पुणे येथील ट्रिपसाठी ₹५८४ मिळाले आहेत.',
      'Information We Collect': 'आमच्या द्वारे गोळा करण्यात आलेली माहिती',
      'We collect personal information that you provide to us, such as your name, phone number, email address and location when you use our services.': 'तुम्ही आमच्या सेवा वापरता तेव्हा तुम्ही आम्हाला तुमचे नाव, फोन नंबर, ईमेल पत्ता आणि ठिकाण (लोकेशन) वगेरे सारखी दिलेली वैयक्तिक माहिती आम्ही गोळा करतो.',
      'How We Use Your Information': 'आम्ही तुमच्या माहितीचा वापर कसा करतो',
      'We use your information to provide, maintain and improve our services, process transactions, communicate with you and ensure safety and security.': 'आम्ही तुमच्या माहितीचा वापर आमच्या सेवा पुरवण्यासाठी, राखण्यासाठी आणि सुधारण्यासाठी, व्यवहारांवर प्रक्रिया करण्यासाठी, तुमच्याशी संवाद साधण्यासाठी आणि सुरक्षितता सुनिश्चित करण्यासाठी करतो.',
      'Information Sharing': 'माहिती शेअर करणे (सामायिक करणे)',
      'We do not sell your personal data.': 'आम्ही तुमचा वैयक्तिक डेटा विकत नाही.',
      'We may share your information with trusted service providers only to deliver our services and comply with legal obligations.': 'आम्ही तुमची माहिती केवळ आमच्या सेवा देण्यासाठी आणि कायदेशीर दायित्वे पूर्ण करण्यासाठी विश्वसनीय सेवा प्रदात्यांसोबत शेअर करू शकतो.',
      'Data Security': 'डेटा सुरक्षा',
      'We implement industry-standard security measures to protect your data from unauthorized access, misuse or disclosure.': 'तुमच्या डेटाचे अनधिकृत प्रवेश, गैरवापर किंवा उघड होण्यापासून संरक्षण करण्यासाठी आम्ही उद्योग-मानक सुरक्षा उपाय लागू करतो.',
      'Your Choices': 'तुमचे पर्याय',
      'You can update your information, manage your preferences or delete your account at any time through the app settings.': 'तुम्ही ॲप सेटिंग्जद्वारे कधीही तुमची माहिती अपडेट करू शकता, तुमच्या पसंती व्यवस्थापित करू शकता किंवा तुमचे खाते हटवू शकता.',
      'Questions or Concerns?': 'प्रश्न किंवा शंका?',
      'Contact our support team at support@metersay.com': 'आमच्या मदत टीमशी support@metersay.com वर संपर्क साधा',
      'Who We Are': 'आम्ही कोण आहोत',
      'Metersay is a technology-driven platform connecting riders with professional drivers for safe, reliable and affordable journeys.': 'Metersay हे एक तंत्रज्ञानावर आधारित प्लॅटफॉर्म आहे जे सुरक्षित, विश्वासार्ह आणि परवडणाऱ्या प्रवासासाठी प्रवाशांना व्यावसायिक चालकांशी (ड्रायव्हर्सशी) जोडते.',
      'Our Mission': 'आमचे ध्येय',
      'To make every ride convenient, comfortable and accessible while creating opportunities for drivers to earn and grow.': 'ड्रायव्हर्सना कमावण्याची आणि प्रगती करण्याची संधी निर्माण करून देत प्रत्येक राईड सोयीस्कर, आरामदायी आणि सुलभ बनवणे.',
      'Our Vision': 'आमचा दृष्टिकोण (व्हिजन)',
      'To become the most trusted mobility platform that drives positive change in the way people and cities move.': 'लोकांच्या आणि शहरांच्या प्रवासाच्या पद्धतीत सकारात्मक बदल घडवून आणणारा सर्वात विश्वासार्ह मोबिलिटी प्लॅटफॉर्म बनणे.',
      'Our Values': 'आमची मूल्ये',
      'We prioritize the safety of our riders and drivers.': 'आम्ही आमच्या प्रवाशांच्या आणि ड्रायव्हर्सच्या सुरक्षिततेला प्राधान्य देतो.',
      'We believe in transparency and honest service.': 'आमचा पारदर्शकता आणि प्रामाणिक सेवेवर विश्वास आहे.',
      'Our customers are at the heart of everything we do.': 'आमचे ग्राहक आम्ही करत असलेल्या प्रत्येक गोष्टीच्या केंद्रस्थानी आहेत.',
      'Edit Profile': 'प्रोफाईल संपादित करा',
      'Tap to change profile photo': 'प्रोफाईल फोटो बदलण्यासाठी टॅप करा',
      'Full Name': 'पूर्ण नाव',
      'Unique ID': 'युनिक आयडी (Unique ID)',
      'Address': 'पत्ता',
      'Save Changes': 'बदल जतन करा',
      'Cancel': 'रद्द करा',
      'Change Password': 'पासवर्ड बदला',
      'Current Password': 'चालू पासवर्ड',
      'New Password': 'नवीन पासवर्ड',
      'Update Password': 'पासवर्ड अपडेट करा',
      'Select Your Preferred Language': 'तुमची पसंतीची भाषा निवडा',
      'Choose the language you want to use in the app.': 'तुम्ही ॲपमध्ये वापरू इच्छित असलेली भाषा निवडा.',
      'Document Expiring Soon': 'कागदपत्राची मुदत लवकरच संपणार आहे',
      'Your Driving License will expire on 12 May 2025.': 'तुमचे ड्रायव्हिंग लायसन्स १२ मे २०२५ रोजी कालबाह्य होईल.',
      'Special Offer': 'विशेष ऑफर',
      'Complete 20 rides this week and get extra ₹300 bonus.': 'या आठवड्यात २० राईड्स पूर्ण करा आणि अतिरिक्त ₹३०० बोनस मिळवा.',
      'Account Verified': 'खाते सत्यापित झाले',
      'Congratulations! Your account has been successfully verified.': 'अभिनंदन! तुमचे खाते यशस्वीरित्या सत्यापित झाले आहे.',
      'Keep your documents updated.': 'तुमची कागदपत्रे अद्ययावत ठेवा.',
      'Expired documents may affect your ride requests.': 'मुदत संपलेली कागदपत्रे तुमच्या राईड विनंत्यांवर परिणाम करू शकतात.',
      'Enable Push Notifications': 'पुश नोटिफिकेशन्स सक्षम करा',
      'Get real-time updates and never miss important alerts.': 'रिअल-टाइम अपडेट मिळवा आणि महत्त्वाच्या सूचना कधीही चुकवू नका.',
      'Update Now': 'आता अपडेट करा',
      'Total Trips': 'एकूण ट्रिप्स (फेऱ्या)',
      'Total Distance': 'एकूण अंतर',
      'Todays Rides': 'आजच्या राईड्स',
      'Rides Completed': 'पूर्ण केलेल्या राईड्स',
      'Ride Request': 'राईडची विनंती',
      'Swipe to Accept': 'स्वीकार करण्यासाठी स्वाइप करा',
      'Accept Ride': 'राईड स्वीकारा',
      'Swipe right to accept rides': 'राईड्स स्वीकारण्यासाठी उजवीकडे स्वाइप करा',
      'Reject': 'नकार द्या (रिजेक्ट करा)',
      'Previous Trips': 'मागील ट्रिप्स',
      'Completed': 'पूर्ण झाले',
      'Customer': 'ग्राहक',
      'Distance': 'अंतर',
      'Meter Based': 'मीटर आधारित',
      'DL Number': 'DL नंबर',
      'Vehicle Registration': 'वाहन नोंदणी',
      'Vehicle Number': 'वाहन क्रमांक',
      'Aadhaar Card': 'आधार कार्ड',
      'Upload front side of your driving license.': 'तुमच्या ड्रायव्हिंग लायसन्सची पुढची बाजू अपलोड करा.',
      'Upload front side of your RC.': 'तुमच्या आरसीची (RC) पुढची बाजू अपलोड करा.',
      'Upload front side of your rickshaw.': 'तुमच्या रिक्षाची पुढची बाजू अपलोड करा.',
      'Upload front side of your Aadhaar.': 'तुमच्या आधार कार्डची पुढची बाजू अपलोड करा.',
      'Upload front side of your PAN.': 'तुमच्या पॅन कार्डची पुढची बाजू अपलोड करा.',
      'Verified': 'सत्यापित केलेले',
      'Chat With Us': 'आमच्याशी चॅट करा',
      'Welcome to Metersay Support': 'Metersay मदत केंद्रात आपले स्वागत आहे',
      'How can we help you today?': 'आज आम्ही तुम्हाला कशी मदत करू शकतो?',
      'Support Assistant': 'सपोर्ट असिस्टंट',
      'Type your message...': 'तुमचा संदेश टाईप करा...',
      'Account & Profile Help': 'खाते आणि प्रोफाईल मदत',
      'Ride Related Issues': 'राईडशी संबंधित समस्या',
      'Promotions & Offers': 'प्रमोशन्स आणि ऑफर्स',
      'Find solutions for issues related to your account and profile.': 'तुमच्या खात्याशी आणि प्रोफाईलशी संबंधित समस्यांवर उपाय शोधा.',
      'We\'re here to help you with any ride related issues.': 'राईडशी संबंधित कोणत्याही समस्येसाठी आम्ही तुम्हाला मदत करण्यास तयार आहोत.',
      'Find answers to all your questions related to promotions and offers.': 'प्रमोशन्स आणि ऑफर्सशी संबंधित तुमच्या सर्व प्रश्नांची उत्तरे शोधा.',
      'Common Account Issues': 'खात्याशी संबंधित सामान्य समस्या',
      'Login Issues': 'लॉगिनच्या समस्या',
      'Mobile Number Update': 'मोबाईल नंबर अपडेट',
      'Email Address Update': 'ईमेल पत्ता अपडेट',
      'Profile Information': 'प्रोफाईल माहिती',
      'Account Deactivation': 'खाते निष्क्रिय करणे',
      'Common Ride Issues': 'राईडशी संबंधित सामान्य समस्या',
      'Wrong Pickup or Drop Location': 'चुकीचे पिकअप किंवा ड्रॉप लोकेशन',
      'Trip Cancelled by User': 'वापरकर्त्याद्वारे ट्रिप रद्द केली',
      'Trip Duration or Distance': 'ट्रिपचा कालावधी किंवा अंतर',
      'Fare or Price Issues': 'भाडे किंवा किमतीच्या समस्या',
      'Route Related Issues': 'मार्गाशी संबंधित समस्या',
      'Common Promotions & Offers Issues': 'प्रमोशन्स आणि ऑफर्सशी संबंधित सामान्य समस्या',
      'Promo Code Not Working': 'प्रोमो कोड काम करत नाही आहे',
      'Offer Not Received': 'ऑफर मिळाली नाही',
      'Offer Validity & Expiry': 'ऑफरची वैधता आणि मुदत समाप्ती',
      'Missed Bonus or Incentive': 'चुकलेला बोनस किंवा इन्सेन्टिव्ह',
      'Incorrect Bonus Amount': 'चुकीची बोनस रक्कम',
      'Still Need Help?': 'अजूनही मदतीची गरज आहे का?',
      'Our support team is available 24/7 to assist you.': 'आमची मदत टीम तुमच्या मदतीसाठी २४/७ उपलब्ध आहे.',
      'Chat with Us': 'आमच्याशी चॅट करा',
      'Email Us': 'आम्हाला ईमेल करा',
      'support@metersay.com': 'support@metersay.com',
      'Unable to Login': 'लॉगिन करता येत नाही आहे',
      'I can\'t login to my account.': 'मी माझ्या खात्यात लॉगिन करू शकत नाही.',
      'I forgot my password.': 'मी माझा पासवर्ड विसरलो आहे.',
      'Didn\'t Receive OTP': 'OTP मिळाला नाही',
      'I didn\'t receive the OTP on my mobile number.': 'मला माझ्या मोबाईल नंबरवर OTP मिळाला नाही.',
      'OTP Not Working': 'OTP काम करत नाही आहे',
      'The OTP I received isn\'t working.': 'मला मिळालेला OTP काम करत नाही आहे.',
      'Account Locked': 'खाते लॉक झाले आहे',
      'My account has been locked.': 'माझे खाते लॉक केले गेले आहे.',
      'How to Update Your Mobile Number': 'तुमचा मोबाईल नंबर कसा अपडेट करावा',
      'Step 1: Go to Profile > Account Settings.': 'पायरी १: प्रोफाईल > खाते सेटिंग्सवर जा.',
      'Step 2: Tap on Mobile Number.': 'पायरी २: मोबाईल नंबरवर टॅप करा.',
      'Step 3: Enter your new mobile number.': 'पायरी ३: तुमचा नवीन मोबाईल नंबर प्रविष्ट करा.',
      'Step 4: Verify the new number with OTP.': 'पायरी ४: OTPद्वारे नवीन नंबर सत्यापित करा.',
      'Step 5: Your mobile number will be updated successfully.': 'पायरी ५: तुमचा मोबाईल नंबर यशस्वीरित्या अपडेट केला जाईल.',
      'How to Update Your Email Address': 'तुमचा ईमेल पत्ता कसा अपडेट करावा',
      'Step 2: Tap on Email Address.': 'पायरी २: ईमेल पत्त्यावर टॅप करा.',
      'Step 3: Enter your new email address.': 'पायरी ३: तुमचा नवीन ईमेल पत्ता प्रविष्ट करा.',
      'Step 4: Verify the email by clicking on the link.': 'पायरी ४: लिंकवर क्लिक करून ईमेल सत्यापित करा.',
      'Step 5: Your email address will be updated successfully.': 'पायरी ५: तुमचा ईमेल पत्ता यशस्वीरित्या अपडेट केला जाईल.',
      'How to Deactivate Your Account': 'तुमचे खाते निष्क्रिय कसे करावे',
      'Step 2: Tap on Account Deactivation.': 'पायरी २: खाते निष्क्रिय करा (अकाउंट डीएक्टिव्हेशन) वर टॅप करा.',
      'Step 3: Select a reason for deactivation.': 'पायरी ३: निष्क्रिय करण्याचे कारण निवडा.',
      'Step 4: Review important information before proceeding.': 'पायरी ४: पुढे जाण्यापूर्वी महत्त्वाच्या माहितीचे पुनरावलोकन करा.',
      'Step 5: Confirm your request to deactivate your account.': 'पायरी ५: तुमचे खाते निष्क्रिय करण्याच्या विनंतीची पुष्टी करा.',
  },
  };

  static String getText(String key) {

    return text[selectedLanguage]![key] ?? key;

  }
}